### ISSUE TITLE
Linked translation as a rich default text

### ISSUE THREAD

**Issue by DmytroMeleshko** [Tienisto/slang#116]
Is it currently possible to use linked translation as a default text for rich text? Something like that:

```
auth:
  termsOfService: Terms of Service
  privacyPolicy: Privacy Policy
  termsAndPolicy(rich): ${terms(@:auth.termsOfService)} & ${policy(@:privacyPolicy)}
```
