### ISSUE TITLE
Image in readme has old variable syntax

### ISSUE THREAD

**Issue by spydon** [Tienisto/slang#122]
**Describe the bug**
The image that is in the readme (and therefore on pub.dev) contains the old fast_i18n variable syntax, with `{variable}` instead of `$variable`.

**Expected behavior**
Correct syntax in readme (and docs).

**Comment by Tienisto** [comment]
Hi, `slang` supports multiple syntaxes. `$variable`, `{variable}` and `{{variable}}` are valid, you can configure it in `string_interpolation`

**Comment by spydon** [comment]
Interesting, I have probably done something wrong then.
I am migrating from fast_i18n to slang and I now realized that I have:
```
targets:
  $default:
    builders:
      slang:
        options:
          ...
          string_interpolation: braces
```
in my `build.yaml` file, but it only works if I use `$`, which seems to be the default?

**Comment by Tienisto** [comment]
You need to import `slang_build_runner` and use it in the yaml:

```yaml
targets:
  $default:
    builders:
      slang_build_runner: // <--
        options:
          ...
          string_interpolation: braces
```
