### ISSUE TITLE
Generate enum keys

### ISSUE THREAD

**Issue by fzyzcjy** [Tienisto/slang#78]
Example:

```
someKey:
  apple: Apple Pie
  orange: Orange Juice
  rpi: Raspberry PI!
```

with pre-defined enum

```
enum Thing { apple, orange, rpi }
```

Hope slang could generate something like:

```
String get(Thing thing) => {
  Thing.apple: 'Apple Pie',
  Thing.orange: 'Orange Juice',
  Thing.rpi: 'Raspberry PI!',
}[thing]!
```

**Comment by Tienisto** [comment]
This is only for one key right? Or should this be applied to multiple ones?

**Comment by Tienisto** [comment]
You can checkout "Custom Contexts". There you have a variety of options. Each "context" is basically an enum

**Comment by fzyzcjy** [comment]
Mainly one key. But may also want multiple isolated keys like:

```
someKey:
  apple: Apple Pie
  orange: Orange Juice
  rpi: Raspberry PI!
someOtherKey:
  apple: AAA
  orange: OOO
  rpi: RRR
```

(Well this is a bad example indeed...)

Thanks!

**Comment by fzyzcjy** [comment]
> You can checkout "Custom Contexts". There you have a variety of options. Each "context" is basically an enum

Thanks, but in my case, I have *predefined* enums, instead of letting slang to do it.

**Comment by Tienisto** [comment]
If I understood this correctly, then only auto detection of enum keys is missing.

```yaml
contexts:
  my_enum:
    paths:
      - someKey
      - someOtherKey
    # actual enum will be determined
```

**Comment by offline-first** [comment]
Please check the new enhanced enum feature `Dart SDK 2.17`:

```dart
enum MyEnum {
  someKey("some_key"),
  someOtherKey("some_other_key");
  final String value;
  const MyEnum(this.value);
}
```

BTW nice new package name

**Comment by offline-first** [comment]
Oh sorry, I didn't follow the entire discussion

**Comment by fzyzcjy** [comment]
In my hand-written code I have:

```
enum Thing { apple, orange, rpi } // written by hand
```

And I want `slang` to *use* that enum directly. Instead of slang *generating* a brand new enum.

**Comment by Tienisto** [comment]
The generated `strings.g.dart` file has to import this file containing the hand-written enum. Hmm... I don't know if this is possible.

**Comment by fzyzcjy** [comment]
> has to import this file containing the hand-written enum. Hmm... I don't know if this is possible. Currently, there is no inspection of dart code

Maybe let the user to specify where the enum is

**Comment by Tienisto** [comment]
Added in `slang 2.4.0`.

Here is your config following the `Thing` example:

```yaml
imports:
  - 'package:my_package/path_to_enum.dart' # define where your enum is
contexts:
  Thing:
    enum:
      - apple
      - orange
      - rpi
    default_parameter: thing
    generate_enum: false # turn off enum generation
```
