### ISSUE TITLE
Does not support uppercase context(enum) names

### ISSUE THREAD

**Issue by fzyzcjy** [Tienisto/slang#86]
```
contexts:
  GenderContext:
    enum:
      - MALE
      - FEMALE
```

i18n yaml

```
  greet:
    MALE: a
    FEMALE: b
```

Then do not understand GenderContext, but instead generate as if MALE and FEMALE are normal keys.
