### ISSUE TITLE
Rich text with string_interpolation=braces has a bug to generate methods

### ISSUE THREAD

**Issue by emersonsiega** [Tienisto/slang#89]
**Describe the bug**
When generating a Rich text using the braces configuration in string_interpolation, the simple variables works fine, but methods with parameters are not being recognized.

**To Reproduce**
I'm using the same string example given in the documentation:
```json
{
  "myText(rich)": "Welcome $name. Please click ${underline(here)}!"
}
```

build.yaml:
```
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          string_interpolation: dart
```

Generated file:
```dart
InlineSpan myText({required InlineSpan name, required InlineSpanBuilder underline}) => TextSpan(children: [
		const TextSpan(text: 'Welcome '),
		name,
		const TextSpan(text: '. Please click '),
		underline('here'),
		const TextSpan(text: '!'),
	]);
```

Changing the settings to braces:
```json
{
  "myText(rich)": "Welcome {name}. Please click {underline(here)}!"
}
```

build.yaml:
```
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          string_interpolation: braces
```

Generated file:
```dart
	InlineSpan myText({required InlineSpan name}) => TextSpan(children: [
		const TextSpan(text: 'Welcome '),
		name,
		const TextSpan(text: '. Please click {underline(here)}!'),
	]);
```

**Expected behavior**
string_interpolation=braces should have the same result as string_interpolation=dart
