### ISSUE TITLE
build_runner with custom output_file_name only works first time

### ISSUE THREAD

**Issue by stefan-schweiger** [Tienisto/slang#90]
**Describe the bug**
When I run `flutter pub run build_runner build --delete-conflicting-outputs` with the following `build.yaml` the first time it generates the correct `translations.g.dart` file. But when I run the command a second time it generates nothing (if you delete the file you won't get a new one). If I change the `output_file` to something else it works again for one time and breaks again afterwards.

```
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          output_file_name: translations.g.dart
```

For the same reason `flutter pub run build_runner watch --delete-conflicting-outputs` also doesn't work for me.

**Expected behavior**
The file should be regenerated each time the command is run.

**Additional context**
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  intl: ^0.17.0
  slang: ^2.6.1
  slang_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  slang_build_runner: ^2.6.0
```

**Additional question**
Why is the `--delete-conflicting-outputs` needed in the first place? Libs like `auto_route` and `json_serializable` don't seem to need the flag to work.
